[versions]
ktor = "3.3.3"

kotlin = "2.3.0"
coroutines = "1.10.2"
io = "0.8.2"
bignum = "0.3.10"
kotlinx-serialization = "1.9.0"

dokka = "2.1.0"
kotlinter = "5.3.0"
deteKT = "1.23.8"
publisher = "0.35.0"
binvalid = "0.18.1"
kover = "0.9.4"

kotest = "6.0.7"
logback = "1.5.23"
rtestcontainers = "2.2.4"

ksp = "2.3.4"
poet = "2.2.0"
autoservice-annotations = "1.1.1"
autoservice-ksp = "1.2.0"

[libraries]
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
serde-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
serde-json-io = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-io", version.ref = "kotlinx-serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
publisher = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publisher" }

# testing
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-cotest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
test-kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
testcontainers-redis = { module = "com.redis:testcontainers-redis", version.ref = "rtestcontainers" }

autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice-annotations" }
autoService-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoservice-ksp" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
poet = { module = "com.squareup:kotlinpoet", version.ref = "poet" }
poet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "poet" }
ksp-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
ktlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
deteKT = { id = "io.gitlab.arturbosch.detekt", version.ref = "deteKT" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-binvalid = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binvalid" }
kotlin-serde = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }