[versions]
ktor = "3.0.1"

kotlin = "2.0.21"
coroutines = "1.9.0"
io = "0.5.4"
datetime = "0.6.1"
bignum = "0.3.10"

dokka = "1.9.20"
kotlinter = "4.4.1"
deteKT = "1.23.7"
publisher = "0.30.0"
binvalid = "0.16.3"
kover = "0.8.3"

kotest = "5.9.1"
logback = "1.5.12"

[libraries]
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls", version.ref = "ktor" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
publisher = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publisher" }

# testing
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
test-kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
deteKT = { id = "io.gitlab.arturbosch.detekt", version.ref = "deteKT" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-binvalid = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binvalid" }