[versions]
ktor = "3.1.3"

kotlin = "2.1.20"
coroutines = "1.10.2"
io = "0.7.0"
datetime = "0.6.2"
bignum = "0.3.10"
kotlinx-serialization = "1.8.1"

dokka = "2.0.0"
kotlinter = "5.0.2"
deteKT = "1.23.8"
publisher = "0.31.0"
binvalid = "0.17.0"
kover = "0.9.1"

kotest = "5.9.1"
logback = "1.5.18"

[libraries]
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls", version.ref = "ktor" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
serde-json-io = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-io", version.ref = "kotlinx-serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
publisher = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publisher" }

# testing
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
test-kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
ktlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
deteKT = { id = "io.gitlab.arturbosch.detekt", version.ref = "deteKT" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-binvalid = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binvalid" }
kotlin-serde = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }