name: Packages Cleanup

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  cleanup:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_name: [
          "eu.vendeli.rethis",
          "eu.vendeli.rethis-androidnativearm32",
          "eu.vendeli.rethis-androidnativearm64",
          "eu.vendeli.rethis-androidnativex64",
          "eu.vendeli.rethis-androidnativex86",
          "eu.vendeli.rethis-iosarm64",
          "eu.vendeli.rethis-iossimulatorarm64",
          "eu.vendeli.rethis-iosx64",
          "eu.vendeli.rethis-js",
          "eu.vendeli.rethis-jvm",
          "eu.vendeli.rethis-linuxarm64",
          "eu.vendeli.rethis-linuxx64",
          "eu.vendeli.rethis-macosarm64",
          "eu.vendeli.rethis-macosx64",
          "eu.vendeli.rethis-mingwx64",
          "eu.vendeli.rethis-mingwx64",
          "eu.vendeli.rethis-tvosarm64",
          "eu.vendeli.rethis-tvossimulatorarm64",
          "eu.vendeli.rethis-tvosx64",
          "eu.vendeli.rethis-watchosarm32",
          "eu.vendeli.rethis-watchosarm64",
          "eu.vendeli.rethis-watchossimulatorarm64",
          "eu.vendeli.rethis-watchosx64",
          "eu.vendeli.rethis-wasm-js",
          
          "eu.vendeli.rethis-shared",
          "eu.vendeli.rethis-shared-androidnativearm32",
          "eu.vendeli.rethis-shared-androidnativearm64",
          "eu.vendeli.rethis-shared-androidnativex64",
          "eu.vendeli.rethis-shared-androidnativex86",
          "eu.vendeli.rethis-shared-iosarm64",
          "eu.vendeli.rethis-shared-iossimulatorarm64",
          "eu.vendeli.rethis-shared-iosx64",
          "eu.vendeli.rethis-shared-js",
          "eu.vendeli.rethis-shared-jvm",
          "eu.vendeli.rethis-shared-linuxarm64",
          "eu.vendeli.rethis-shared-linuxx64",
          "eu.vendeli.rethis-shared-macosarm64",
          "eu.vendeli.rethis-shared-macosx64",
          "eu.vendeli.rethis-shared-mingwx64",
          "eu.vendeli.rethis-shared-mingwx64",
          "eu.vendeli.rethis-shared-tvosarm64",
          "eu.vendeli.rethis-shared-tvossimulatorarm64",
          "eu.vendeli.rethis-shared-tvosx64",
          "eu.vendeli.rethis-shared-watchosarm32",
          "eu.vendeli.rethis-shared-watchosarm64",
          "eu.vendeli.rethis-shared-watchossimulatorarm64",
          "eu.vendeli.rethis-shared-watchosx64",
          "eu.vendeli.rethis-shared-wasm-js",
        ]
    steps:
      - name: Delete old versions of ${{ matrix.package_name }}
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-type: maven
          package-name: ${{ matrix.package_name }}
          min-versions-to-keep: 10
